### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by humaidkidwai** [Upsolver/iceberg-diag#9]
Just installed the tool and ran a help command. 

`iceberg-diag --help

Traceback (most recent call last):
  File "/home/humaid/.local/bin/iceberg-diag", line 5, in <module>
    from icebergdiag.cli import cli_runner
  File "/home/humaid/.local/lib/python3.8/site-packages/icebergdiag/cli.py", line 20, in <module>
    from icebergdiag.metrics.table_metrics_displayer import TableMetricsDisplayer, RunMode
  File "/home/humaid/.local/lib/python3.8/site-packages/icebergdiag/metrics/table_metrics_displayer.py", line 16, in <module>
    class TableMetricsDisplayer:
  File "/home/humaid/.local/lib/python3.8/site-packages/icebergdiag/metrics/table_metrics_displayer.py", line 21, in TableMetricsDisplayer
    def display_metrics(self, tables: list[TableMetrics], mode: RunMode) -> None:
TypeError: 'type' object is not subscriptable`

**Comment by efrotenberg** [comment]
Hi @humaidkidwai ,

Thank you for reporting the issue. The bug is the type hinting syntax (`list[Type]`) which is only supported in Python 3.9 and later, instead of `List[Type]`.
 Your current Python version (3.8) does not support this syntax.

As a temporary solution, you can upgrade to Python 3.9 or higher to resolve the issue

[Update] Fixed in latest version: [commit](https://github.com/Upsolver/iceberg-diag/commit/b1f5aa97a040b2ea382ab5cfae51dfbe33241a24)
